function parTableRel = suspOpt_param_rangeRelative
% suspOpt_param_rangeRelative   Produce table of values for suspension parameter tuning
%   parTableRel = suspOpt_param_rangeRelative
%   This function produces a table listing suspension parameters for
%   tuning.  Each row contains 
%
%       Label       Short label to identify parameter
%       Parameter   Path to parameter in data structure used in model
%       Index       Index of referenced value (hardpoints are [x, y, z])
%       Use         True or False if parameter should be tuned
%       Min         Minimum of range for parameter value
%                    This is an offset from default for hardpoints
%                    This is the actual value for scalar parameters
%       Max         Maximum of range for parameter value
%                    This is an offset from default for hardpoints
%                    This is the actual value for scalar parameters

% Copyright 2023-2025 The MathWorks, Inc.


tblVariableNames = ["Label","Parameter","Index","Use","Min","Max"];

varNamesRel = {...
    'HP_A1_UA_inFx','Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.sInboardF.Value',1,true,-0.01*5,0.01*5;...
    'HP_A1_UA_inFy','Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.sInboardF.Value',2,true,-0.01*5,0.01*5;...
    'HP_A1_UA_inFz','Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.sInboardF.Value',3,true,-0.01*5,0.01*5;...
    'HP_A1_UA_inRx','Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.sInboardR.Value',1,true,-0.01*5,0.01*5;...
    'HP_A1_UA_inRy','Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.sInboardR.Value',2,true,-0.01*5,0.01*5;...
    'HP_A1_UA_inRz','Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.sInboardR.Value',3,true,-0.01*5,0.01*5;...
    'HP_A1_UA_Outx','Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.sOutboard.Value',1,true,-0.01*5,0.01*5;...
    'HP_A1_UA_Outy','Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.sOutboard.Value',2,true,-0.01*5,0.01*5;...
    'HP_A1_UA_Outz','Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.sOutboard.Value',3,true,-0.01*5,0.01*5;...
    'HP_A1_LA_inFx','Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.sInboardF.Value',1,true,-0.01*5,0.01*5;...
    'HP_A1_LA_inFy','Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.sInboardF.Value',2,true,-0.01*5,0.01*5;...
    'HP_A1_LA_inFz','Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.sInboardF.Value',3,true,-0.01*5,0.01*5;...
    'HP_A1_LA_inRx','Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.sInboardR.Value',1,true,-0.01*5,0.01*5;...
    'HP_A1_LA_inRy','Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.sInboardR.Value',2,true,-0.01*5,0.01*5;...
    'HP_A1_LA_inRz','Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.sInboardR.Value',3,true,-0.01*3,0.01*5;...
    'HP_A1_LA_Outx','Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.sOutboard.Value',1,true,-0.01*5,0.01*5;...
    'HP_A1_LA_Outy','Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.sOutboard.Value',2,true,-0.01*5,0.01*5;...
    'HP_A1_LA_Outz','Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.sOutboard.Value',3,true,-0.01*5,0.01*5;...
    'HP_A1_Ro_Inbx','Vehicle.Chassis.SuspA1.Linkage.TrackRod.sInboard.Value'      ,1,true,-0.01*5,0.01*5;...
    'HP_A1_Ro_Inby','Vehicle.Chassis.SuspA1.Linkage.TrackRod.sInboard.Value'      ,2,true,-0.01*5,0.01*5;...
    'HP_A1_Ro_Inbz','Vehicle.Chassis.SuspA1.Linkage.TrackRod.sInboard.Value'      ,3,true,-0.01*3,0.01*3;...
    'HP_A1_Ro_Outx','Vehicle.Chassis.SuspA1.Linkage.TrackRod.sOutboard.Value'     ,1,true,-0.01*5,0.01*5;...
    'HP_A1_Ro_Outy','Vehicle.Chassis.SuspA1.Linkage.TrackRod.sOutboard.Value'     ,2,true,-0.01*5,0.01*5;...
    'HP_A1_Ro_Outz','Vehicle.Chassis.SuspA1.Linkage.TrackRod.sOutboard.Value'     ,3,true,-0.01*3,0.01*5;...
    'HP_A1_Sh_Topx','Vehicle.Chassis.SuspA1.Linkage.Shock.sTop.Value',             1,true,-0.01*5,0.01*5;...
    'HP_A1_Sh_Topy','Vehicle.Chassis.SuspA1.Linkage.Shock.sTop.Value',             2,true,-0.01*5,0.01*5;...
    'HP_A1_Sh_Topz','Vehicle.Chassis.SuspA1.Linkage.Shock.sTop.Value',             3,true,-0.01*5,0.01*5;...
    'HP_A1_Sh_Botx','Vehicle.Chassis.SuspA1.Linkage.Shock.sBottom.Value',          1,true,-0.01*3,0.01*3;...
    'HP_A1_Sh_Boty','Vehicle.Chassis.SuspA1.Linkage.Shock.sBottom.Value',          2,true,-0.01*3,0.01*3;...
    'HP_A1_Sh_Botz','Vehicle.Chassis.SuspA1.Linkage.Shock.sBottom.Value',          3,true,-0.01*3,0.01*3;...
    'HP_A1_Up_CGrx','Vehicle.Chassis.SuspA1.Linkage.Upright.sCG.Value'            ,1,true,-0.01*2,0.01*2;...
    'HP_A1_Up_CGry','Vehicle.Chassis.SuspA1.Linkage.Upright.sCG.Value'            ,2,true,-0.01*2,0.01*2;...
    'HP_A1_Up_CGrz','Vehicle.Chassis.SuspA1.Linkage.Upright.sCG.Value'            ,3,true,-0.01*2,0.01*2;...
    'HP_A1_Up_WCtx','Vehicle.Chassis.SuspA1.Linkage.Upright.sWheelCentre.Value'   ,1,true,-0.01*5,0.01*5;...
    'HP_A1_Up_WCty','Vehicle.Chassis.SuspA1.Linkage.Upright.sWheelCentre.Value'   ,2,true,-0.01*5,0.01*5;...
    'HP_A1_Up_WCtz','Vehicle.Chassis.SuspA1.Linkage.Upright.sWheelCentre.Value'   ,3,true,-0.01*5,0.01*5;...
    'HP_A1_AR_Inbx','Vehicle.Chassis.SuspA1.AntiRollBar.sInboard.Value'           ,1,true,-0.01*5,0.01*5;...
    'HP_A1_AR_Inby','Vehicle.Chassis.SuspA1.AntiRollBar.sInboard.Value'           ,2,true,-0.01*5,0.01*5;...
    'HP_A1_AR_Inbz','Vehicle.Chassis.SuspA1.AntiRollBar.sInboard.Value'           ,3,true,-0.01*5,0.01*5;...
    'HP_A1_AR_Outx','Vehicle.Chassis.SuspA1.AntiRollBar.sOutboard.Value'          ,1,true,-0.01*5,0.01*5;...
    'HP_A1_AR_Outy','Vehicle.Chassis.SuspA1.AntiRollBar.sOutboard.Value'          ,2,true,-0.01*5,0.01*5;...
    'HP_A1_AR_Outz','Vehicle.Chassis.SuspA1.AntiRollBar.sOutboard.Value'          ,3,true,-0.01*5,0.01*5;...
    ...
    'Da_A1_Da_damp','Vehicle.Chassis.Damper.Axle1.Damping.d.Value'                ,1,true,5000-1000, 6600+1000;...
    'Da_A1_En_xMin','Vehicle.Chassis.Damper.Axle1.Endstop.xMin.Value'             ,1,true,-0.0875,-0.085;...
    'Da_A1_En_xMax','Vehicle.Chassis.Damper.Axle1.Endstop.xMax.Value'             ,1,true, 0.0625, 0.065;...
    'Sp_A1_Sp_Stif','Vehicle.Chassis.Spring.Axle1.K.Value'                        ,1,true,51000-5000,53000+5000;...
    'Ar_A1_AR_Stif','Vehicle.Chassis.SuspA1.AntiRollBar.k.Value'                  ,1,true,27-5,33+5;...
    ...
    'HP_A2_UA_inFx','Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.sInboardF.Value',1,true,-0.01*5,0.01*5;...
    'HP_A2_UA_inFy','Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.sInboardF.Value',2,true,-0.01*5,0.01*5;...
    'HP_A2_UA_inFz','Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.sInboardF.Value',3,true,-0.01*5,0.01*5;...
    'HP_A2_UA_inRx','Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.sInboardR.Value',1,true,-0.01*5,0.01*5;...
    'HP_A2_UA_inRy','Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.sInboardR.Value',2,true,-0.01*5,0.01*5;...
    'HP_A2_UA_inRz','Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.sInboardR.Value',3,true,-0.01*5,0.01*5;...
    'HP_A2_UA_Outx','Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.sOutboard.Value',1,true,-0.01*5,0.01*5;...
    'HP_A2_UA_Outy','Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.sOutboard.Value',2,true,-0.01*5,0.01*5;...
    'HP_A2_UA_Outz','Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.sOutboard.Value',3,true,-0.01*5,0.01*5;...
    'HP_A2_LA_inFx','Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.sInboardF.Value',1,true,-0.01*5,0.01*5;...
    'HP_A2_LA_inFy','Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.sInboardF.Value',2,true,-0.01*5,0.01*5;...
    'HP_A2_LA_inFz','Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.sInboardF.Value',3,true,-0.01*5,0.01*5;...
    'HP_A2_LA_inRx','Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.sInboardR.Value',1,true,-0.01*5,0.01*5;...
    'HP_A2_LA_inRy','Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.sInboardR.Value',2,true,-0.01*5,0.01*5;...
    'HP_A2_LA_inRz','Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.sInboardR.Value',3,true,-0.01*5,0.01*5;...
    'HP_A2_LA_Outx','Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.sOutboard.Value',1,true,-0.01*5,0.01*5;...
    'HP_A2_LA_Outy','Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.sOutboard.Value',2,true,-0.01*5,0.01*5;...
    'HP_A2_LA_Outz','Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.sOutboard.Value',3,true,-0.01*5,0.01*5;...
    'HP_A2_Ro_Inbx','Vehicle.Chassis.SuspA2.Linkage.TrackRod.sInboard.Value'      ,1,true,-0.01*5,0.01*5;...
    'HP_A2_Ro_Inby','Vehicle.Chassis.SuspA2.Linkage.TrackRod.sInboard.Value'      ,2,true,-0.01*5,0.01*5;...
    'HP_A2_Ro_Inbz','Vehicle.Chassis.SuspA2.Linkage.TrackRod.sInboard.Value'      ,3,true,-0.01*3,0.01*3;...
    'HP_A2_Ro_Outx','Vehicle.Chassis.SuspA2.Linkage.TrackRod.sOutboard.Value'     ,1,true,-0.01*2,0.01*2;...
    'HP_A2_Ro_Outy','Vehicle.Chassis.SuspA2.Linkage.TrackRod.sOutboard.Value'     ,2,true,-0.01*2,0.01*2;...
    'HP_A2_Ro_Outz','Vehicle.Chassis.SuspA2.Linkage.TrackRod.sOutboard.Value'     ,3,true,-0.01*3,0.01*2;...
    'HP_A2_Sh_Topx','Vehicle.Chassis.SuspA2.Linkage.Shock.sTop.Value',             1,true,-0.01*5,0.01*5;...
    'HP_A2_Sh_Topy','Vehicle.Chassis.SuspA2.Linkage.Shock.sTop.Value',             2,true,-0.01*5,0.01*5;...
    'HP_A2_Sh_Topz','Vehicle.Chassis.SuspA2.Linkage.Shock.sTop.Value',             3,true,-0.01*5,0.01*5;...
    'HP_A2_Sh_Botx','Vehicle.Chassis.SuspA2.Linkage.Shock.sBottom.Value',          1,true,-0.01*3,0.01*3;...
    'HP_A2_Sh_Boty','Vehicle.Chassis.SuspA2.Linkage.Shock.sBottom.Value',          2,true,-0.01*3,0.01*3;...
    'HP_A2_Sh_Botz','Vehicle.Chassis.SuspA2.Linkage.Shock.sBottom.Value',          3,true,-0.01*3,0.01*3;...
    'HP_A2_Up_CGrx','Vehicle.Chassis.SuspA2.Linkage.Upright.sCG.Value'            ,1,true,-0.01*2,0.01*2;...
    'HP_A2_Up_CGry','Vehicle.Chassis.SuspA2.Linkage.Upright.sCG.Value'            ,2,true,-0.01*2,0.01*2;...
    'HP_A2_Up_CGrz','Vehicle.Chassis.SuspA2.Linkage.Upright.sCG.Value'            ,3,true,-0.01*2,0.01*2;...
    'HP_A2_Up_WCtx','Vehicle.Chassis.SuspA2.Linkage.Upright.sWheelCentre.Value'   ,1,true,-0.01*5,0.01*5;...
    'HP_A2_Up_WCty','Vehicle.Chassis.SuspA2.Linkage.Upright.sWheelCentre.Value'   ,2,true,-0.01*5,0.01*5;...
    'HP_A2_Up_WCtz','Vehicle.Chassis.SuspA2.Linkage.Upright.sWheelCentre.Value'   ,3,true,-0.01*5,0.01*5;...
    'HP_A2_AR_Inbx','Vehicle.Chassis.SuspA2.AntiRollBar.sInboard.Value'           ,1,true,-0.01*5,0.01*5;...
    'HP_A2_AR_Inby','Vehicle.Chassis.SuspA2.AntiRollBar.sInboard.Value'           ,2,true,-0.01*5,0.01*5;...
    'HP_A2_AR_Inbz','Vehicle.Chassis.SuspA2.AntiRollBar.sInboard.Value'           ,3,true,-0.01*5,0.01*5;...
    'HP_A2_AR_Outx','Vehicle.Chassis.SuspA2.AntiRollBar.sOutboard.Value'          ,1,true,-0.01*5,0.01*5;...
    'HP_A2_AR_Outy','Vehicle.Chassis.SuspA2.AntiRollBar.sOutboard.Value'          ,2,true,-0.01*5,0.01*5;...
    'HP_A2_AR_Outz','Vehicle.Chassis.SuspA2.AntiRollBar.sOutboard.Value'          ,3,true,-0.01*5,0.01*5;...
    'Da_A2_Da_damp','Vehicle.Chassis.Damper.Axle2.Damping.d.Value'                ,1,true,5000-1000,6600+1000;...
    'Da_A2_En_xMin','Vehicle.Chassis.Damper.Axle2.Endstop.xMin.Value'             ,1,true,-0.0875,-0.085;...
    'Da_A2_En_xMax','Vehicle.Chassis.Damper.Axle2.Endstop.xMax.Value'             ,1,true, 0.0625, 0.065;...
    'Sp_A2_Sp_Stif','Vehicle.Chassis.Spring.Axle2.K.Value'                        ,1,true,51000-5000,53000+5000;...
    'Ar_A2_AR_Stif','Vehicle.Chassis.SuspA2.AntiRollBar.k.Value'                  ,1,true,45-5,55+5;...
    };

parTableRel = cell2table(varNamesRel);
parTableRel.Properties.VariableNames = tblVariableNames;
