% -------------------------------------------------------------------
%  Generated by MATLAB on 21-Dec-2023 22:40:52
%  MATLAB version: 23.2.0.2459199 (R2023b) Update 5
% -------------------------------------------------------------------
                                    

Init = struct;
Init.Instance = 'Sedan_Hamba';
Init.Type = 'Double_Lane_Change_ISO3888';
Init.Chassis = struct;
Init.Chassis.aChassis = struct;
Init.Chassis.aChassis.Units = 'rad';
Init.Chassis.aChassis.Value = [0 0 0];
Init.Chassis.aChassis.Comments = 'Roll-Pitch-Yaw';
Init.Chassis.vChassis = struct;
Init.Chassis.vChassis.Units = 'm/s';
Init.Chassis.vChassis.Value = [2.5 0 0];
Init.Chassis.vChassis.Comments = '';
Init.Chassis.sChassis = struct;
Init.Chassis.sChassis.Units = 'm';
Init.Chassis.sChassis.Value = [5 -3.35+0.4 0.025];
Init.Chassis.sChassis.Comments = '';
Init.Axle1 = struct;
Init.Axle1.nWheel = struct;
Init.Axle1.nWheel.Units = 'rad/s';
Init.Axle1.nWheel.Comments = 'Values are [left right]';
Init.Axle1.nWheel.Value = [7.1429 7.1429 0.35];
Init.Axle2 = struct;
Init.Axle2.nWheel = struct;
Init.Axle2.nWheel.Units = 'rad/s';
Init.Axle2.nWheel.Comments = 'Values are [left right]';
Init.Axle2.nWheel.Value = [7.1429 7.1429 0.35];

